### ISSUE TITLE
Ability to fully override environment

### ISSUE THREAD

**Issue by danpalmer** [DanielSincere/Sh#3]
It would be great to have the option to fully specify the environment used, rather than specifying additional variables to be combined with the current process's environment.

**Comment by DanielSincere** [comment]
I agree this would be nice

**Comment by danpalmer** [comment]
I considered implementing this but actually realised that for my use-case I do want to inherit the environment so I don't need this. Feel free to leave open if you want the feature request, but also feel free to close as I won't be implementing this myself.

**Comment by DanielSincere** [comment]
Yeah, that's exactly how I've felt about this. Environment isolation would be nice, and I always end up needing something from the outside environment 😅
